### ISSUE TITLE
webpack argument should be color

### ISSUE THREAD

**Issue by justAnotherDev** [thesmythgroup/sentimentalist#1]
thanks for the great tutorial! when running `npm run build` it errs saying:

```
> webpack --progress --colors

[webpack-cli] Unknown argument: --colors
Did you mean --color?
```

[This](https://github.com/thesmythgroup/sentimentalist/blob/master/JS/package.json#L7) line should be changed to:

```
"build": "webpack --progress --color"
```

If you'd like I can create a PR, but figured it'd probably just be easier/quicker for you to change it directly.

**Comment by jfahrenkrug** [comment]
Hey Casey, thanks so much for reporting this. Webpack has indeed changed the name of that argument, I'll fix it :) Thanks again!

**Comment by jfahrenkrug** [comment]
Hey Casey, how did you install the packages? I just checked it out and followed these steps:

```
cd JS
npm install
npm run build
```

That worked fine, because the `package-lock.json` file specifies the older webpack version, which used `--colors`. Could you try if those steps work for you too? I'll close the ticket for now, feel free to reopen it if you still run into issues.

**Comment by justAnotherDev** [comment]
you are correct, if you use the existing code everything is fine. the issue arises if you follow the tutorial and run the commands yourself.

```
npm init --yes
npm install webpack --save-dev
```

this uses the current version of webpack and makes it so `--colors` is not a valid param.

the two simple solutions i see would be to either:

- update the tutorial by changing the command to force an old version of webpack (`npm install webpack@3.8.1 --save-dev`)
- update the repo to use a current version of webpack and the correct `--color` param. 

really annoying that they would change a param name and not backwards support it..

**Comment by jfahrenkrug** [comment]
@justAnotherDev Hey Casey, just wanted to let you know that I've updated the Medium blog post to say `--color` :) Thanks again.
