### ISSUE TITLE
Not working under MacOS 10.15.7 and XCode 12

### ISSUE THREAD

**Issue by TiPunch69** [thesmythgroup/sentimentalist#2]
I tried to get the sample to run on Mac OS 10.15.7 with XCode 12.

Everything looks fine, except the result of the Javascript call always returns undefined. It also seems that the function does not "really" get called, as I can alter its name with little effect.

I used webpack 5 (with production mode) and NPM 7.6.0.

**Comment by jfahrenkrug** [comment]
@TiPunch69 Hi Michael, thanks for the feedback. It might have something to do with how webpack has changes since we first released the article. How is the behavior when you checkout this project and run `npm install`, so the versions specified in the package-lock.json are used?

**Comment by TiPunch69** [comment]
I tried it with the library versions provided and it works (with a few vulerabilities). I then upgraded the libraries to the current versions and now it stopped working.
```
  "devDependencies": {
    "webpack": "^5.33.2",
    "webpack-cli": "^4.6.0"
  },
  "dependencies": {
    "sentiment": "^5.0.2"
  }
```
 The Javascript now produces an error, which can be seen by adding an error handler.
```
self.context.exceptionHandler = {
            context, exception in
            NSLog("Javascript Error : " + (exception?.toString())!)
        }
```
I think the problem is with the new version of webpack. Would be great to get an update of the code that works with the current version of NPM libraires.

**Comment by jfahrenkrug** [comment]
@TiPunch69 Part of the problem was that the newest version of the sentiment package included changes that made it necessary to call it differently. It's fixed in this PR: https://github.com/thesmythgroup/sentimentalist/pull/8 I'll update the tutorial article next week.
